### ISSUE TITLE
splatnet2statink has updated breaking the script

### ISSUE THREAD

**Issue by Zhomb** [Valerokai/Splatnet2-Rich-Presence#3]
splatnet2statink has updated (probably due to 4.0 update) and now the script throws an exception at line 23 [matches = load_results()] the only way to get around this is to install an older version of splatnet2statink

**Comment by Valerokai** [comment]
Tested working - now it's sorted, remove all files related to splatnet2statink (currently dbs.py, iksm.py, splatnet2statink.py, and the splatnet2statink folder), then rerun the install script, to get everything set back up again using the new fixed version. I'm leaving this issue open while I sort out a better way to solve this.

**Comment by Valerokai** [comment]
Yeah, of course, I'm going to spend some time later today moving everything across into my own implementation later to remove the requirement for S2S - however though, I did just update myself and it *seems* to be working without modifications, and without the filename param?

**Comment by frozenpandaman** [comment]
No worries! Just wanted to make sure we're on the same page. :D And let me know if there's anything I can do to help.

It should be working now, yeah – I put the if statement which references the (non-existent, when you call s2s's `load_results()` before the main method) `filename` variable in a try/except block. So when your script calls it, it'll just `pass` over it since naturally it doesn't exist. The method now taking a param was another issue but I fixed that as well.

**Comment by Zhomb** [comment]
Thanks you both for explaining the problem! I'm trying to get into the Splatoon API too and this should help. Besides that thanks for the fix to the script, I really appreciate it.

**Comment by frozenpandaman** [comment]
No problem! Unless you need specific user data like battle records, the splatoon2.ink API will be useful too.

P.S. Nice Pyukumuku avatar.
